services:
  nacos:
    container_name: nacos
    image: nacos/nacos-server:v2.1.0-slim
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      cluster-net:
        ipv4_address: 172.29.0.10

  mysql:
    image: mysql:8.0.29
    container_name: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - C:/Dev/Tools/Docker/volumes/mysql_data:/var/lib/mysql
    privileged: true
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      cluster-net:
        ipv4_address: 172.29.0.30

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      cluster-net:
        ipv4_address: 172.29.0.40

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      cluster-net:
        ipv4_address: 172.29.0.50

networks:
  cluster-net:
    driver: bridge      # 指定网络驱动类型为桥接（bridge）
    ipam:
      config:
        - subnet: 172.29.0.0/24